Improve models and new DAOs
AndrewLiaIH/inholland-year1-term4-project-building-applications pull request #7
Opened 2024-05-22 12:55 UTC by AndrewLiaIH

DAOs are incomplete; will need to add a method in BaseDao for GetById queries

2024-05-22 14:12 UTC, AnastasiaIU commented on DAL/EmployeeDAO.cs
> +    public class EmployeeDAO : BaseDAO
Please, follow the naming conventions for C#, e.g. BaseDao.

Naming example:
https://learn.microsoft.com/en-us/cpp/mfc/reference/cdaoworkspace-class?view=msvc-170

2024-05-22 14:18 UTC, AnastasiaIU commented on DAL/EmployeeDAO.cs
> +    public class EmployeeDAO : BaseDAO
Same for ID, it should be Id

2024-05-22 14:29 UTC, AnastasiaIU requested changes
Please, change the naming with accordance to the convetion and finish the method GetEmployeeById.

2024-05-22 15:43 UTC, OrestPokotylenko requested changes
The same thing what Sia said, pleace change the namings. It looks good for the rest

2024-05-23 18:25 UTC, AnastasiaIU approved these changes
Looks good

2024-05-23 18:27 UTC, OrestPokotylenko approved these changes

2024-05-23 18:37 UTC, merged